name: Latest WP Support

on:
  schedule:
    - cron: "0 2 5 * *" # Every month on the 5th at 2am UTC

jobs:
  is-outdated:
    name: Check if WP version is outdated
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master

      - name: Check wp version
        uses: tarosky/farmhand-wp-action@v1.0.0
        id: wp_version
        with:
          readme: README.md

      - name: Update Issue if needed
        if: steps.wp_version.outputs.should_update
        uses: actions-ecosystem/action-create-issue@v1
        with:
          github_token: ${{ secrets.github_token }}
          title: Update to ${{ steps.wp_version.outputs.version }}
          body: |
            ## TODO

            - [ ] Check if plugin works with the latest WP version
            - [ ] Bump "Tested up to" version in README.md

          labels: |
            update
          assignees: |
            fumikito
